### ISSUE TITLE
Fails to load, import error

### ISSUE THREAD

**Issue by aurel-g** [nsdtcloud3d/ComfyUI-3D-Convert#1]
Hi

On Linux with Python 3.11 I got this errors at ComfyUI's startup:

```
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-3D-Convert/__init__.py", line 2, in <module>
    from util.nsdt import upload_file_to_nsdt, convert_to_target_file
ModuleNotFoundError: No module named 'util'
```

**Comment by nsdtcloud3d** [comment]
thanks ! !
